### ISSUE TITLE
./node_modules/react-instagram-zoom-slider/dist/index.es.js Module not found: Can't resolve 'react-spring' in 'C:\Users\binda\Desktop\painting webite\nepalese-artworks\node_modules\react-instagram-zoom-slider\dist'

### ISSUE THREAD

**Issue by ujjwal66** [skozer/react-instagram-zoom-slider#18]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## Expected behavior

(A clear and concise description of what you expected to happen.)

## Link to example (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-instagram-zoom-slider` v1.x.x
- `react-spring` v8.x.x
- `react-use-gesture` v7.0.x
- `styled-components` v5.0.x
- `react` v16.12.x

**Comment by skozer** [comment]
Hi @ujjwal66,

`react-spring` is a peer dependency of this library - please see the installation instructions:

https://github.com/skozer/react-instagram-zoom-slider#install
