### ISSUE TITLE
Positions element

### ISSUE THREAD

**Issue by K073** [skozer/react-instagram-zoom-slider#7]
If I have many sliders one after another, then when zooming in, the bottom slider overlays on top of the zoomed image

**Comment by skozer** [comment]
Thanks for reporting @K073!
I will take a look at it this week

**Comment by skozer** [comment]
Fixed in 1.4.0

**Comment by prannavmaytray** [comment]
If you want an alternative for this, I recommend checking out this [Instagram carousel downloader](https://reelit.io/instagram-carousel)
